#!/usr/bin/env bash
# Central theme generator.
# Edit ~/.config/theme/theme.json, then run this script to propagate the
# font + colors into every app and reload them.
set -euo pipefail

CFG="${XDG_CONFIG_HOME:-$HOME/.config}"
T="$CFG/theme/theme.json"

command -v jq >/dev/null 2>&1 || { echo "error: jq is required (sudo pacman -S jq)"; exit 1; }
[ -f "$T" ] || { echo "error: $T not found"; exit 1; }


j() { jq -r "$1" "$T"; }

# Font:
MONO=$(j '.font.mono')
MONO_STRICT=$(j '.font.monoStrict')
EMOJI=$(j '.font.emoji')
SZ_TERM=$(j '.font.size.terminal')
SZ_BAR=$(j '.font.size.bar')
SZ_NOTIFY=$(j '.font.size.notify')
SZ_GTK=$(j '.font.size.gtk')

# Color:
BG=$(j '.color.background')
FG=$(j '.color.foreground')
AC=$(j '.color.accent')
MU=$(j '.color.muted')
UR=$(j '.color.urgent')
hex() { echo "${1#\#}"; }          # strip a leading '#'

# General:
CR=$(j '.general.corner_radius')
BS=$(j '.general.border_size')

echo ":: generating configs from $T"

# --- kitty (included from kitty.conf) ---
cat > "$CFG/kitty/theme.conf" <<EOF
# generated by ~/.config/theme/apply.sh -- do not edit by hand
font_family          $MONO_STRICT
font_size            $SZ_TERM
foreground           $FG
background           $BG
cursor               $AC
selection_background $AC
selection_foreground $BG
EOF

# --- mako (no include mechanism -> whole file is generated) ---
cat > "$CFG/mako/config" <<EOF
# generated by ~/.config/theme/apply.sh -- do not edit by hand
font=$MONO $SZ_NOTIFY
background-color=${BG}ee
text-color=$FG
border-color=$AC
width=360
height=120
margin=10
padding=12
border-size=$BS
border-radius=$CR
default-timeout=5000
anchor=top-right

# toggled by SUPER+CTRL+COMMA -> makoctl mode -t do-not-disturb
[mode=do-not-disturb]
invisible=1
EOF

# --- hyprlock palette (sourced by hyprlock.conf as \$font/\$background/...) ---
cat > "$CFG/hypr/hypr-theme.conf" <<EOF
# generated by ~/.config/theme/apply.sh -- do not edit by hand
\$font = $MONO
\$background = rgb($(hex "$BG"))
\$foreground = rgb($(hex "$FG"))
\$accent = rgb($(hex "$AC"))
EOF
# note: \$wallpaper is written separately by wallpaper.sh (the current image),
# so the lock screen tracks whatever wallpaper is showing.

# --- fontconfig ---
# cat > "$CFG/fontconfig/fonts.conf" <<EOF
# <?xml version="1.0"?>
# <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
# <fontconfig>
#   <!-- generated by ~/.config/theme/apply.sh -->
#   <alias binding="strong"><family>emoji</family><prefer><family>$EMOJI</family></prefer></alias>
#   <alias><family>monospace</family><prefer><family>$MONO</family></prefer></alias>
#   <match target="pattern"><test name="family"><string>monospace</string></test>
#     <edit name="family" mode="append" binding="weak"><string>$EMOJI</string></edit></match>
#   <match target="pattern"><test name="family"><string>$MONO</string></test>
#     <edit name="family" mode="append" binding="weak"><string>$EMOJI</string></edit></match>
#   <match target="pattern"><test name="family"><string>sans-serif</string></test>
#     <edit name="family" mode="append" binding="weak"><string>$EMOJI</string></edit></match>
#   <match target="pattern"><test name="family"><string>serif</string></test>
#     <edit name="family" mode="append" binding="weak"><string>$EMOJI</string></edit></match>
# </fontconfig>
# EOF

# --- GTK 3 & 4 (font line only; colors come from the gtk theme package) ---
for ini in "$CFG/gtk-3.0/settings.ini" "$CFG/gtk-4.0/settings.ini"; do
  if [ -f "$ini" ]; then
    sed -i "s|^gtk-font-name=.*|gtk-font-name=$MONO $SZ_GTK|" "$ini"
  fi
done

# --- quickshell (merge font+color into theme.json, preserve layout keys) ---
QT="$CFG/quickshell/config/theme.json"
if [ -f "$QT" ]; then
  tmp=$(mktemp)
  jq --arg mono "$MONO" \
     --arg icon "$MONO_STRICT" \
     --argjson size "$SZ_BAR" \
     --arg bg "$BG" \
     --arg fg "$FG" \
     --arg ac "$AC" \
     --arg mu "$MU" \
     --arg ur "$UR" \
     '.fontText=$mono 
    | .fontIcon=$icon 
    | .fontSize=$size
    | .background=$bg 
    | .foreground=$fg 
    | .accent=$ac 
    | .muted=$mu 
    | .urgent=$ur' \
     "$QT" > "$tmp" && mv "$tmp" "$QT"
fi

# --- hyprland window font ---
if [ -f "$CFG/hypr/looknfeel.lua" ]; then
  sed -i "s|font_family = \".*\"|font_family = \"$MONO\"|" "$CFG/hypr/looknfeel.lua"
fi

# --- reload everything that can be reloaded live ---
echo ":: reloading"
fc-cache -f >/dev/null 2>&1 || true
if [ -n "$(pidof kitty 2>/dev/null || true)" ]; then kill -SIGUSR1 "$(pidof kitty)" 2>/dev/null || true; fi
makoctl reload 2>/dev/null || true
hyprctl reload >/dev/null 2>&1 || true
# restart hyprpaper and re-apply the current wallpaper (wallpaper.sh relaunches
# hyprpaper itself and waits for its IPC, so no '&&' race here).
pkill hyprpaper 2>/dev/null || true
"$CFG/theme/wallpaper.sh" init >/dev/null 2>&1 || true
# quickshell watches theme.json and hot-reloads on its own.

notify-send -t 500 "theme reloaded" 