#!/usr/bin/env bash
# Wallpaper cycler for hyprpaper.
# Steps sequentially through the images in the directory named by
# ~/.config/theme/theme.json  ->  .wallpaper.dir , driving hyprpaper over IPC.
# hyprpaper has no native directory/cycle support, so this script is what makes
# "point at a folder and flip through it" work.
#
# It also writes the current image into hypr-wallpaper.conf so hyprlock's
# lock-screen background matches whatever wallpaper is showing.
#
# Usage: wallpaper.sh [next|prev|init]
#   next  - advance to the next image   (bound to SUPER+CTRL+SPACE)
#   prev  - step back one image
#   init  - (re)apply the current image; used at login and after apply.sh
set -euo pipefail

CFG="${XDG_CONFIG_HOME:-$HOME/.config}"
T="$CFG/theme/theme.json"
STATE="${XDG_STATE_HOME:-$HOME/.local/state}/wallpaper-current"
WPCONF="$CFG/hypr/hypr-wallpaper.conf"   # sourced by hyprlock -> $wallpaper

DIR=$(jq -r '.wallpaper.dir' "$T")
[ -d "$DIR" ] || { echo "wallpaper: '$DIR' is not a directory (set .wallpaper.dir in theme.json)"; exit 1; }

# Sorted list of images in the directory (top level only).
mapfile -t IMGS < <(find "$DIR" -maxdepth 1 -type f \
  \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' -o -iname '*.bmp' \) \
  | sort)
N=${#IMGS[@]}
[ "$N" -gt 0 ] || { echo "wallpaper: no images found in $DIR"; exit 1; }

# Where are we now? (state file holds the current image path)
CURRENT=""
[ -f "$STATE" ] && CURRENT=$(cat "$STATE")
idx=-1
for i in "${!IMGS[@]}"; do [ "${IMGS[$i]}" = "$CURRENT" ] && { idx=$i; break; }; done

case "${1:-next}" in
  next) idx=$(( (idx + 1) % N )) ;;
  prev) idx=$(( (idx - 1 + N) % N )) ;;
  init) [ "$idx" -lt 0 ] && idx=0 ;;      # first run / removed image -> start at first
  *)    echo "usage: wallpaper.sh [next|prev|init]"; exit 2 ;;
esac
TARGET="${IMGS[$idx]}"

# Ensure hyprpaper is running and its IPC is answering (login race-safe).
if ! pgrep -x hyprpaper >/dev/null; then hyprpaper >/dev/null 2>&1 & fi
for _ in $(seq 1 50); do
  hyprctl hyprpaper listactive >/dev/null 2>&1 && break
  sleep 0.1
done

# Preload the target, show it on every monitor, then drop the previous image
# so we keep at most one wallpaper in memory.
hyprctl hyprpaper preload "$TARGET"    >/dev/null 2>&1 || true
hyprctl hyprpaper wallpaper ",$TARGET" >/dev/null
if [ -n "$CURRENT" ] && [ "$CURRENT" != "$TARGET" ]; then
  hyprctl hyprpaper unload "$CURRENT"  >/dev/null 2>&1 || true
fi

# Persist state and expose the current image to hyprlock as $wallpaper.
mkdir -p "$(dirname "$STATE")"
echo "$TARGET" > "$STATE"
printf '# generated by wallpaper.sh -- current wallpaper, sourced by hyprlock\n$wallpaper = %s\n' "$TARGET" > "$WPCONF"
